accountApp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountApp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountApp'
urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountApp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleApp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountApp.urls')),
    path('profiles/', include('profileApp.urls')),
    path('articles/', include('articleApp.urls')),
    path('comments/', include('commentApp.urls')),
    path('projects/', include('projectApp.urls')),
    path('subscriptions/', include('subscriptionApp.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileApp/urls.py
from profileApp.views import ProfileCreateView, ProfileUpdateView
from django.urls import path
app_name = 'profileApp'
urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountApp/models.py
from django.db import models

articleApp/models.py
from django.contrib.auth.models import User
from django.db import models
from projectApp.models import Project
class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)
    created_at = models.DateField(auto_created=True, null=True)

accountApp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountApp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountApp.decorators import account_ownership_required
from accountApp.forms import AccountUpdateForm
from articleApp.models import Article

has_ownership = [account_ownership_required, login_required]

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'accountApp/create.html'

class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountApp/detail.html'
    paginate_by = 20
    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('home')
    template_name = 'accountApp/update.html'

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountApp:login')
    template_name = 'accountApp/delete.html'

accountApp/templates/accountApp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style = "text-align:center; max-width:500px; margin:4rem auto">
        <div class="mb-4">
            <h4>
                SignUp
            </h4>
        </div>
        <form action="{% url 'accountApp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

accountApp/templates/accountApp/delete.html
{% extends 'base.html' %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>
            Quit
        </h4>
    </div>
    <form action="{% url 'accountApp:delete' target_user.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountApp/templates/accountApp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div style="text-align: center; max-width=500px; margin: 4rem; auto;">
            <p>
                {{ target_user.date_joined }}
            </p>
            <!-- object-fit 요런거 원래 css로 다 빼야한대 -->
            <img src="{{ target_user.profile.image.url }}" alt="" style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit:cover;">
            {% if target_user.profile %}
            <h2 style="font-family: 'NanumSquareRoundOTFB'">
                {{ target_user.nickname }}
                    {% if target_user == user %}
                    <a class="material-icons" style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;" href="{% url 'profileApp:update' pk=target_user.profile.pk %}">
                        edit
                    </a>
                    {% endif %}
            </h2>
            {% else %}
                {% if target_user == user %}
                <a href="{% url 'profileApp:create'%}">
                    <h2 style="font-family: 'NanumSquareRoundOTFB'">
                        Create Profile
                    </h2>
                </a>
                {% else %}
                <h2>
                    닉네임 미설정
                </h2>
                {% endif %}
            {% endif %}
            <h5 style="margin-bottom: 3rem";>
                {{ target_user.profile.message }}
            </h5>
            {% if target_user == user %}
            <a class="material-icons" style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;" href="{% url 'accountApp:update' pk=target_user.pk %}">
                <p>
                    settings
                </p>
            </a>
            <a class="material-icons" style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;" href="{% url 'accountApp:delete' pk=target_user.pk %}">
                <p>
                    cancel
                </p>
            </a>
            {% endif %}
        </div>
        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>
    </div>
{% endblock %}

accountApp/templates/accountApp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div style="text-align: center; max-width:500px; margin:4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-3 mt-3">
            </form>
        </div>
    </div>
{% endblock %}

accountApp/templates/accountApp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>
            Change Info
        </h4>
    </div>
    <form action="{% url 'accountApp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}