accountApp/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountApp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountApp'
urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='accountApp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleApp/urls.py
from django.views.generic import TemplateView
from django.urls import path

from articleApp.views import ArticleUpdateView, ArticleCreateView, ArticleDetailView, ArticleDeleteView, ArticleListView

app_name = 'articleApp'
urlpatterns =[
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
    path('list/', ArticleListView.as_view(), name='list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from articleApp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountApp.urls')),
    path('profiles/', include('profileApp.urls')),
    path('articles/', include('articleApp.urls')),
    path('comments/', include('commentApp.urls')),
    path('projects/', include('projectApp.urls')),
    path('subscriptions/', include('subscriptionApp.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectApp/urls.py
from django.urls import path

from projectApp.views import ProjectListView, ProjectDetailView, ProjectCreateView

app_name = 'projectApp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),

]

subscriptionApp/urls.py
from django.urls import path

from subscriptionApp.views import SubscriptionView, SubscriptionListView

app_name = 'subscriptionApp'

urlpatterns = [
    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}

<body style="font-family:'NanumSquareRoundOTFB'">
    {% include 'header.html' %}
    <hr>

    {% block content %}
    {% endblock %}

    <hr>
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
    <div class="pinterest_footer">
        <div class="pinterest_footer_button">
            <span>공지사항</span>
            <span>제휴문의</span>
            <span>서비스 소개</span>
        </div>
        <div style="margin-top: 1rem;">
            <h6 class="pinterest_logo">pinterest</h6>
        </div>
    </div>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>pinterest</title>

    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- GOOGLE FONTS LINK -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kurale&display=swap" rel="stylesheet">

    <!-- GOOGLE METERIAL ICONS -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">

    <style>
        @font-face {
            font-family: "NanumSquareRoundOTFB";
            src: local("NanumSquareRoundOTFB"),
            url("{% static 'fonts/NanumSquareRoundOTFB.otf' %}" format("opentype"))
        }
        @font-face {
            font-family: "NanumSquareRoundOTFEB";
            src: local("NanumSquareRoundOTFEB"),
            url("{% static 'fonts/NanumSquareRoundOTFEB.otf' %}" format("opentype"))
        }
        @font-face {
            font-family: "NanumSquareRoundOTFL";
            src: local("NanumSquareRoundOTFL"),
            url("{% static 'fonts/NanumSquareRoundOTFL.otf' %}" format("opentype"))
        }
        @font-face {
            font-family: "NanumSquareRoundOTFR";
            src: local("NanumSquareRoundOTFR"),
            url("{% static 'fonts/NanumSquareRoundOTFR.otf' %}" format("opentype"))
        }
    </style>
</head>

templates/header.html
    <div class="pinterest_header">
        <div class="pinterest_logo">
            <h1>pinterest</h1>
        </div>
        <div class="pinterest_header_navbar">
            <a href="{% url 'articleApp:list' %}" class="pinterest_header_nav">
                <span>Articles</span>
            </a>
            <a href="{% url 'projectApp:list' %}" class="pinterest_header_nav">
                <span>Projects</span>
            </a>
            <!-- 로그인 했을때만 구독정보 누를 수 있게 -->
            {% if user.is_authenticated %}
            <a href="{% url 'subscriptionApp:list' %}" class="pinterest_header_nav">
                <span>Subscription</span>
            </a>
            {% endif %}
            {% if not user.is_authenticated %}
            <a href="{% url 'accountApp:login' %}?next={{ request.path }}" class="pinterest_header_nav">
                <span>login</span>
            </a>
            <a href="{% url 'accountApp:create' %}" class="pinterest_header_nav">
                <span>SignUp</span>
            </a>
            {% else %}
            <a href="{% url 'accountApp:detail' pk=user.pk %}" class="pinterest_header_nav">
                <span>MyPage</span>
            </a>
            <a href="{% url 'accountApp:logout' %}?next={{ request.path }}" class="prgmatic_header_nav">
                <span>logout</span>
            </a>
            {% endif %}
        </div>
    </div>